language: haskell
os: linux
dist: focal

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack path
- stack install hpc-codecov

script:
  - stack --no-terminal --skip-ghc-check --coverage test

after_script:
  - stack hpc report Hudoku
  - hpcroot=$(stack path --local-hpc-root)
  - tix=$(find $hpcroot -name 'test.tix')
  - mix=$(stack path --dist-dir)/hpc
  - hpc-codecov --mix=$mix --exclude=Paths_hpc_codecov -o codecov.json $tix
  - bash <(curl -s https://codecov.io/bash)

