name:                Hudoku
version:             0.1.0.0
github:              "5n00p4eg/hudoku"
license:             BSD3
author:              "Daniil Boiko"
maintainer:          "5n00p4eg@gmail.com"
copyright:           "2021 Daniil Boiko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/githubuser/simple#readme>

dependencies:
- base >= 4.7 && < 5
- boxes
- extra

library:
  source-dirs: src

executables:
  exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - boxes
      - Hudoku
      - extra

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - Hudoku
      - boxes
      - HUnit
      - tasty
      - tasty-hunit
